# Generated by Django 5.1.7 on 2025-03-31 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('template_text', models.TextField(help_text='Use {variable} syntax for placeholders')),
                ('description', models.TextField(blank=True)),
                ('message_type', models.CharField(choices=[('weather', 'Weather Alert'), ('price', 'Price Update'), ('order', 'Order Notification'), ('payment', 'Payment Notification'), ('system', 'System Notification'), ('marketing', 'Marketing Message')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('alert_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('severity', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=10)),
                ('source', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('produce_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_updates', to='marketplace.producecategory')),
            ],
        ),
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_number', models.CharField(max_length=15)),
                ('message_content', models.TextField()),
                ('message_type', models.CharField(choices=[('weather', 'Weather Alert'), ('price', 'Price Update'), ('order', 'Order Notification'), ('payment', 'Payment Notification'), ('system', 'System Notification'), ('marketing', 'Marketing Message')], max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('twilio_sid', models.CharField(blank=True, max_length=50, null=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='marketplace.buyer')),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='marketplace.farmer')),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='marketplace.order')),
                ('related_produce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='marketplace.produce')),
            ],
        ),
        migrations.CreateModel(
            name='SMSSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('weather', 'Weather Alerts'), ('price', 'Price Updates'), ('order', 'Order Notifications'), ('system', 'System Notifications'), ('marketing', 'Marketing Messages')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_subscriptions', to='marketplace.buyer')),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_subscriptions', to='marketplace.farmer')),
            ],
            options={
                'unique_together': {('buyer', 'subscription_type'), ('farmer', 'subscription_type')},
            },
        ),
    ]
